[package]
name                 = "type_ulid_macros"
description          = "Macros for the type_ulid crate."
version              = "0.3.0"
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote       = "1.0.21"
syn         = { version = "1.0.100", features = ["extra-traits"] }
ulid        = { version = "1.0.0", default-features = false }
