[package]
name                    = "bones_schema"
description             = "Simple runtime reflection system designed for scripting."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[features]
default   = ["derive", "serde"]
serde     = ["dep:serde", "dep:erased-serde", "ulid/serde", "bones_utils/serde"]
derive    = ["bones_schema_macros"]
glam      = ["dep:glam"]
humantime = ["dep:humantime", "serde"]

[dependencies]
bones_utils = { version = "0.3", path = "../bones_utils" }
ulid        = { version = "1.1" }
paste       = "1.0"
sptr        = "0.3"

# Optional deps
bones_schema_macros = { version = "0.3", path = "./macros", optional = true }
glam                = { version = "0.24", optional = true }
serde               = { version = "1.0", features = ["derive"], optional = true }
erased-serde        = { version = "0.4", optional = true }
humantime           = { version = "2.1", optional = true }
stable_deref_trait  = "1.2.0"
append-only-vec     = "0.1.3"

[[test]]
name              = "tests"
required-features = ["glam"]

[dev-dependencies]
serde_yaml = "0.9"
