[package]
name                    = "bones_schema"
description             = "Simple runtime reflection system designed for scripting."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[features]
default   = ["derive", "serde"]
serde     = ["dep:serde", "dep:erased-serde", "ulid/serde", "bones_utils/serde"]
derive    = ["bones_schema_macros"]
glam      = ["dep:glam"]
humantime = ["dep:humantime", "serde"]

[dependencies]
append-only-vec    = "0.1.3"
bones_utils        = { version = "0.4.0", path = "../bones_utils" }
fxhash             = { workspace = true }
hashbrown          = { workspace = true }
parking_lot        = { workspace = true }
paste              = "1.0"
sptr               = "0.3"
stable_deref_trait = "1.2.0"
ulid               = "1.0"
ustr               = { workspace = true }

# Optional deps
bones_schema_macros = { version = "0.4.0", path = "./macros", optional = true }
glam                = { version = "0.24", optional = true }
serde               = { version = "1.0", features = ["derive"], optional = true }
erased-serde        = { version = "0.4", optional = true }
humantime           = { version = "2.1", optional = true }

[[test]]
name              = "tests"
required-features = ["glam"]

[dev-dependencies]
serde_yaml = "0.9"

[[example]]
name = "schema_derive"
required-features = ["glam"]
