[package]
name                    = "bones_wgpu_renderer"
description             = "WGPU rendering implementation for the bones_framework."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[dependencies]
bones_framework   = { version = "0.4.0", path = "../bones_framework" }
bones_schema      = { path = "../bones_schema" }
winit             = "0.30.9"
#Needs to be 23 because of bones_bevy_renderer dependecies, we need to upgrade to 24^ later
wgpu              = "23"
pollster          = "0.4.0"
env_logger        = "0.11.6"
log               = "0.4"
bevy_tasks        = "0.11.3"
image             = "0.24.9"
crossbeam-channel = "0.5.14"
bytemuck          = "1.22"

egui              = "0.30"
egui-wgpu         = "0.30"
egui-winit        = "0.30"

serde             = "1.0.188"
serde_yaml        = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories       = "5.0"
