[package]
authors     = ["The Fish Folk & Spicy Lobster Developers"]
description = "Trait for associating ULIDs with Rust types."
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "type_ulid"
repository  = "https://github.com/fishfolk/bones"
version     = "0.2.0"

[features]
default = ["std"]
# Implement TypeUlid for basic types in the standard library
std = []

[dependencies]
type_ulid_macros = { version = "^0.2.0", path = "./macros" }
ulid             = { version = "1.0", default-features = false }
